name: 'spellcheck'
on:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: matheus23/md-spellcheck-action@v4.2.2
        with:
          files-to-check: "**/*.md"
          files-to-exclude: |
            CODE_OF_CONDUCT.md
            CONTRIBUTING.md
            Community_Specification_License-v1.md
            Notices.md
          words-to-ignore-file: ./.github/workflows/words-to-ignore.txt
